### ISSUE TITLE
Using `moduleResolution: bundler` fails to resolve typings

### ISSUE THREAD

**Issue by JoostK** [rars/diff-match-patch-ts#49]
When TypeScript's `bundler` module resolution mode is used (or the stricter `node16`/`nodenext` variants), would an error be reported:

```ts
error TS7016: Could not find a declaration file for module 'diff-match-patch-ts'. 'node_modules/diff-match-patch-ts/diff-match-patch-ts.mjs' implicitly h
as an 'any' type.
  There are types at 'node_modules/diff-match-patch-ts/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'diff-match-patch-ts' library may need to update its package.json or typings.
```

This is because the exports map refers the `types` condition for `import` to a non-existent `index.d.mts` file. I believe the `types` entry should refer to the same `index.d.ts` file as is used for CJS bundles, which should be compatible. When I apply this change manually my build succeeds.

**Note:** I am using 0.5.0, the latest version at time of writing.

**Comment by rars** [comment]
Thanks @JoostK for reporting this. I made the suggested change in [v0.5.1](https://github.com/rars/diff-match-patch-ts/releases/tag/v0.5.1). Please let me know if you still have any problems.

**Comment by JoostK** [comment]
Thank you for addressing it! Unfortunately I've since had to abandon the effort to adopt `bundler` resolution due to some other compatibility issues (IIRC Jest with CJS modules didn't particularly like it), but given that 0.5.1 contains the exact change I patched in at the time this should work.

Thanks again and for maintaining this package in the first place! 🙏
