### ISSUE TITLE
Is this project's MIT license valid?

### ISSUE THREAD

**Issue by 12joan** [rars/diff-match-patch-ts#56]
I'm not a lawyer, but I'm trying to understand whether the diff-match-patch code in this package has been correctly licensed.

As outlined in this repo's [LICENSE.md](https://github.com/rars/diff-match-patch-ts/blob/main/LICENSE.md) file, the original diff-match-patch code belongs to Neil Fraser and was released under the Apache License 2.0. A port of this code to TypeScript appears in Elliot Forbes' repo [ng-diff-match-patch](https://github.com/elliotforbes/ng-diff-match-patch), which has an MIT license.

The part I'm unsure of is whether ng-diff-match-patch's MIT license (and therefore this project's MIT license) is valid. Typically, unless ports are carried out without reference to the source code of the original work, they are considered to be derivative works[^1]. It seems unlikely to me that the TypeScript port was carried out in this manner, so licensing the port under MIT would require Neil Fraser's permission[^2].

Edit: I've emailed Elliot Forbes to ask their perspective on this.

[^1]: https://opensource.stackexchange.com/a/1799
[^2]: https://opensource.stackexchange.com/a/9079

**Comment by elliotforbes** [comment]
Hi @12joan - I'll preface this by saying that I'm not entirely well-versed in licensing laws. It's been a long time since I've written that library and I believe I took the stance at the time that I could retain the MIT license used by the original angular-diff-match-path - https://github.com/amweiss/angular-diff-match-patch - that I'd ported. 

I had assumed that they had done their due diligence with regard to figuring out the appropriate license, however, If I have mis-licensed this, I'm happy to update my license retroactively.

**Comment by 12joan** [comment]
Hi @elliotforbes,

Thanks for providing that additional information. It looks like angular-diff-match-patch depends on the [diff-match-patch package](https://github.com/JackuB/diff-match-patch) via NPM. Unlike copyleft licenses like GPL, software that depends on an Apache 2.0 licensed library can itself be released under any license, which was why angular-diff-match-patch was able to be released under MIT even though the diff-match-patch package was released under Apache 2.0.

Unfortunately, any code taken or modified from diff-match-patch directly can't be relicensed as MIT.

One potential remedy for your ng-diff-match-patch repo (and any other project that contains a mixture of diff-match-patch code and original code) would be to carve out the diff-match-patch code as an exception to the overall project's LICENSE file, such as by placing an additional LICENSE file containing the Apache 2.0 license in a directory containing the diff-match-patch code.

To comply with the Apache 2.0 license's requirement to state changes, it may also be necessary to state in the source files that they've been ported to TypeScript, and also ensure that the notices at the top of the [original source file](https://github.com/JackuB/diff-match-patch/blob/master/index.js) remain intact.

@rars The license of the diff-match-patch-ts package will also have to be changed to Apache 2.0, and its source files should preserve all notices from the [original JS port](https://github.com/JackuB/diff-match-patch/blob/master/index.js), in addition to any notices @elliotforbes chooses to add to the TypeScript port.

To anyone else reading this:
- If you're using diff-match-patch-ts unmodified via NPM, you probably don't need to make any changes.
- If your project contains code duplicated from diff-match-patch-ts, be sure to carve out the duplicated code from any other licenses your project is released under, include a copy of the Apache 2.0 license with the duplicated code, preserve all notices, and state any changes you may have made to the duplicated code.

**Comment by rars** [comment]
Hi @12joan. Thanks for your query. As I've, outlined in the [LICENSE.md](https://github.com/rars/diff-match-patch-ts/blob/main/LICENSE.md) file, it is only the changes introduced by this library that I have licensed under MIT (which I believe I am free to do). The MIT license from @elliotforbes's contributions is also noted and included in the LICENSE.md file. I'm happy to update this if @elliotforbes feels that something has been missed and would like that reflected in this repository.

The existing Apache 2.0 license still applies to the remainder of the code that has persisted unmodified from Neil Fraser's original contribution, this project is not attempting to relicense that. I have preserved these notices in the source files themselves, e.g. [https://github.com/rars/diff-match-patch-ts/blob/main/src/diff-match-patch.class.ts](diff-match-patch.class.ts) and where the code is unmodified, the Apache 2.0 license still applies. Hope this clears things up.

**Comment by 12joan** [comment]
@rars Thanks for your reply. I see now that I hadn't read the LICENSE file carefully enough and had missed the part about only the changes being MIT licensed. My apologies! 😅

I'll close this issue now, since I don't believe there's anything wrong with this package's licensing.

@elliotforbes You may still want to amend your repo to bring it in compliance with the Apache 2.0 license, but since it's an old repo that isn't being distributed as a package, I wouldn't worry too much about it.
